import { FolderOpen, X } from 'lucide-react';
import { useAppStore } from '../store/app-store';
import { Hardware } from './Hardware';
import { InferencePerformance } from './InferencePerformance';

export function Toolbar() {
  const { conversations, activeId, models, hardware, settings, activeContextWindow, updateConversation, performance, isGenerating } = useAppStore();
  const chat = conversations.find((item) => item.id === activeId);
  if (!chat) return null;
  const chooseDirectory = async () => { const directory = await window.localAi.dialog.chooseDirectory(); if (directory) await updateConversation(chat.id, { workingDirectory: directory }); };
  const selectedModel = models.find((model) => model.id === chat.modelId) ?? models[0];
  const contextLabel = `${Math.round((activeContextWindow ?? chat.contextWindow) / 1024)}K`;
  return <header className="toolbar"><div className="monitoring-row" aria-label="Мониторинг runtime"><Hardware value={hardware} /><InferencePerformance value={performance} isGenerating={isGenerating} /><span className="backend-indicator">{settings?.selectedBackend === 'llama-cpp' ? 'llama.cpp · MTP' : 'Ollama'}</span></div><div className="toolbar-controls"><label className="control"><span>Модель</span><select value={chat.modelId ?? ''} onChange={(event) => void updateConversation(chat.id, { modelId: event.target.value || null })}><option value="">Выберите модель</option>{models.map((model) => <option value={model.id} key={model.id} disabled={!model.installed}>{model.name}{model.installed ? '' : ' · не установлена'}</option>)}</select></label><label className="control"><span>Контекст · {contextLabel}</span><select value={chat.contextWindow} onChange={(event) => void updateConversation(chat.id, { contextWindow: Number(event.target.value) })}>{(selectedModel?.supportedContextPresets ?? []).map((preset) => <option value={preset} key={preset}>{Math.round(preset / 1024)}K</option>)}</select></label><label className="control"><span>Глубина</span><select value={chat.analysisDepth} onChange={(event) => void updateConversation(chat.id, { analysisDepth: event.target.value as 'fast' | 'normal' | 'enhanced' | 'deep' })}><option value="fast">Быстрый</option><option value="normal">Обычный</option><option value="enhanced">Повышенный</option><option value="deep">Глубокий</option></select></label><label className="control"><span>Web</span><select value={chat.webMode} onChange={(event) => void updateConversation(chat.id, { webMode: event.target.value as 'off' | 'auto' })}><option value="off">Off</option><option value="auto">Auto</option></select></label><label className="control"><span>Режим</span><select value={chat.mode} onChange={(event) => void updateConversation(chat.id, { mode: event.target.value as 'chat' | 'agent' })}><option value="chat">Чат</option><option value="agent">Агент</option></select></label><div className="directory"><FolderOpen size={16} /><button onClick={() => void chooseDirectory()}>{chat.workingDirectory ?? 'Рабочая папка: не выбрана'}</button>{chat.workingDirectory && <button className="icon-button" aria-label="Убрать рабочую папку" onClick={() => void updateConversation(chat.id, { workingDirectory: null })}><X size={14} /></button>}</div></div></header>;
}
