import { FolderOpen, X } from 'lucide-react';
import { useAppStore } from '../store/app-store';
import { Hardware } from './Hardware';
import { InferencePerformance } from './InferencePerformance';
import { projectDirectoryName } from '../../shared/project-references';

export function Toolbar() {
  const { conversations, activeId, models, hardware, settings, activeContextWindow, updateConversation, performance, isGenerating } = useAppStore();
  const chat = conversations.find((item) => item.id === activeId);
  if (!chat) return null;
  const chooseDirectory = async (slot: 1 | 2, currentDirectory: string | null) => { const directory = await window.localAi.dialog.chooseDirectory(currentDirectory); if (directory) await updateConversation(chat.id, slot === 1 ? { workingDirectory: directory } : { secondaryWorkingDirectory: directory }); };
  const selectedModel = models.find((model) => model.id === chat.modelId) ?? models[0];
  const contextLabel = `${Math.round((activeContextWindow ?? chat.contextWindow) / 1024)}K`;
  const projectSelector = (slot: 1 | 2, directory: string | null) => <div className={`directory project-selector project-${slot}`}><FolderOpen size={16} /><button title={directory ?? undefined} onClick={() => void chooseDirectory(slot, directory)}>{directory ? projectDirectoryName(directory) : `Project ${slot}: не выбран`}</button>{directory && <button className="icon-button" aria-label={`Убрать Project ${slot}`} onClick={() => void updateConversation(chat.id, slot === 1 ? { workingDirectory: null } : { secondaryWorkingDirectory: null })}><X size={14} /></button>}</div>;
  const runtimeLabel = settings?.selectedBackend === 'llama-cpp' ? settings.llamaRuntimeModelId === 'glm-4.7-flash:q4_k' ? 'llama.cpp · GLM-4.7-Flash' : 'llama.cpp · MTP' : 'Ollama';
  return <header className="toolbar"><div className="monitoring-row" aria-label="Мониторинг runtime"><Hardware value={hardware} /><InferencePerformance value={performance} isGenerating={isGenerating} /><span className="backend-indicator">{runtimeLabel}</span></div><div className="toolbar-controls"><label className="control"><span>Модель</span><select value={chat.modelId ?? ''} onChange={(event) => void updateConversation(chat.id, { modelId: event.target.value || null })}><option value="">Выберите модель</option>{models.map((model) => <option value={model.id} key={model.id} disabled={!model.installed}>{model.name}{model.installed ? '' : ' · не установлена'}</option>)}</select></label><label className="control"><span>Контекст · {contextLabel}</span><select value={chat.contextWindow} onChange={(event) => void updateConversation(chat.id, { contextWindow: Number(event.target.value) })}>{(selectedModel?.supportedContextPresets ?? []).map((preset) => <option value={preset} key={preset}>{Math.round(preset / 1024)}K</option>)}</select></label>{selectedModel?.supportsReasoning && <label className="control"><span>Рассуждение</span><select value={chat.reasoningMode} onChange={(event) => void updateConversation(chat.id, { reasoningMode: event.target.value as 'auto' | 'fast' | 'deep' })}><option value="auto">Авто</option><option value="fast">Быстро</option><option value="deep">Глубоко</option></select></label>}<label className="control"><span>Web</span><select value={chat.webMode} onChange={(event) => void updateConversation(chat.id, { webMode: event.target.value as 'off' | 'auto' })}><option value="off">Off</option><option value="auto">Auto</option></select></label><label className="control"><span>Режим</span><select value={chat.mode} onChange={(event) => void updateConversation(chat.id, { mode: event.target.value as 'chat' | 'agent' })}><option value="chat">Чат</option><option value="agent">Агент</option></select></label><div className="project-selectors">{projectSelector(1, chat.workingDirectory)}{projectSelector(2, chat.secondaryWorkingDirectory)}</div></div></header>;
}
