import assert from 'node:assert/strict';
import { useAppStore } from '../renderer/store/app-store';
import { progressIndicatorLabel } from './generation-progress';
import type { StreamEvent } from './types';

Object.defineProperty(globalThis, 'window', { configurable: true, value: { requestAnimationFrame: () => 1, cancelAnimationFrame() {} } });
const store = useAppStore;
const begin = (id: string) => store.setState({ activeId: 'progress', generationId: id, generationConversationId: 'progress', generationOwnerId: id, isGenerating: true, generationState: 'thinking', messages: [{ id: `stream-${id}`, conversationId: 'progress', role: 'assistant', content: '', createdAt: '' }], toolActivities: [] });
let id = 'first';
const send = (event: StreamEvent) => store.getState().handleStream({ ...event, conversationId: 'progress', generationId: id });
const indicator = (agent = false) => progressIndicatorLabel(store.getState().generationState, store.getState().toolActivities, agent);
begin(id); assert.equal(indicator(), 'Ожидаю ответ модели…');
send({ type: 'thinking', content: 'Actual reasoning' }); assert.equal(indicator(), null);
send({ type: 'tool', activity: { id: 'status', label: 'Agent status', kind: 'progress', state: 'running' } }); assert.equal(indicator(), null, 'status metadata must not reset the model streaming phase');
send({ type: 'tool', activity: { id: 'status', label: 'Agent status', kind: 'progress', state: 'completed' } }); assert.equal(indicator(), null);
send({ type: 'token', content: 'Answer' }); assert.equal(indicator(), null);
send({ type: 'tool', activity: { id: 'search', label: 'Поиск в интернете', kind: 'web', state: 'running' } });
assert.equal(indicator(), 'Поиск в интернете'); assert.equal(indicator(true), null, 'Agent timeline already presents the tool');
send({ type: 'tool', activity: { id: 'search', label: 'Поиск в интернете', kind: 'web', state: 'completed' } }); assert.equal(indicator(), 'Ожидаю ответ модели…');
send({ type: 'model-state', state: 'waiting' }); assert.equal(indicator(true), 'Ожидаю ответ модели…');
send({ type: 'model-state', state: 'streaming' }); assert.equal(indicator(), null, 'native fragmented tool calls are model output');
send({ type: 'thinking', content: 'Following up' }); assert.equal(indicator(), null);
send({ type: 'cancelled' }); assert.equal(indicator(), null);
id = 'regenerated'; begin(id);
store.getState().handleStream({ type: 'thinking', content: 'Late old output', conversationId: 'progress', generationId: 'first' });
assert.equal(indicator(), 'Ожидаю ответ модели…', 'stale reasoning must not hide new-round waiting');
send({ type: 'thinking', content: 'New thinking' }); assert.equal(indicator(), null);
send({ type: 'error', message: 'fixture timeout' }); assert.equal(indicator(), null);
console.log('Actual renderer-store progress: per-round waiting/reasoning/content/tools, native fragments, Agent parity, Stop, Regenerate and error passed.');
